name:  Create the customization package
run-name: Creating 01JHU_INST-JHU Customization Package Zip
on: [push, workflow_dispatch]
jobs:
    Build-Assets:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
            
        - name: Use Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: 16.x

        - name: Build
          run: |
            npm install
            gulp cleanJS
            gulp cleanCSS
            gulp scripts
            gulp styles
    Create-Package:
        runs-on: ubuntu-latest
        needs: Build-Assets
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: 01JHU_INST-JHU
                  path: ./**/01JHU_INST-JHU
