name:  Create the customization package
run-name: Creating 01JHU_INST-JHU Customization Package Zip
on: [push, workflow_dispatch]
jobs:
    Create-Pacakge:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: 01JHU_INST-JHU
                  path: ./**/01JHU_INST-JHU
