name:  Create the customization package
run-name: ${{ github.actor }} is creating a customization package for the 01JHU_INST-01JHU_INST primo view
on: [push]
jobs:
    Create-Pacakge:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: 01JHU_INST-01JHU_INST
                  path: views/01JHU_INST-01JHU_INST