name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp scripts
        gulp styles
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: custom.js
        path: vendor/js/custom.js
        retention-days: 7
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: custom1.css
        path: vendor/js/custom1.css
        retention-days: 7


